substitutions:
  device_name: opnpool-1
  friendly_name: "Test external component OPNpool"
  description: "test external component, see https://medium.com/@vinsce/create-an-esphome-external-component-part-1-introduction-config-validation-and-code-generation-e0389e674bd6"

esphome:
  name: ${device_name}
  comment: ${description}
  friendly_name: ${friendly_name}
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"
  # For debugging, store generated code in an accessible location:
  # build_path: "../config/esphome/component_build"

esp32:
  variant: ESP32
  board: esp32dev
  framework:
    type: arduino #esp-idf

logger:
  baud_rate: 0
  
wifi:
  domain: !secret domain_name
  min_auth_mode: WPA2
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap: # enable fallback ap captive portal in case wifi connection fails
    ssid: "${device_name} Config"
    password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key 

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time  

web_server:
  port: 80
  include_internal: true

captive_portal:
    

external_components:
  - source: 
      type: local
      path: components

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  flow_control_pin: GPIO4
  baud_rate: 9600
  debug: # You can even see the raw RS485 traffic in logs!
    direction: BOTH

opnpool:
  uart_id: uart_bus
  pool_heater:
    name: "Pool Heater"
  spa_heater:
    name: "Spa Heater"
  
  pool: { name: "Pool Mode" }
  spa: { name: "Spa Mode" }
  aux1: { name: "Cleaner" }
  aux2: { name: "Waterfall" }
  
  water_temperature: { name: "Pool Water Temperature" }
  air_temperature: { name: "Outside Air Temperature" }
  
  pump_power: { name: "Pump Power" }
  pump_flow: { name: "Pump Flow" }
  pump_running: { name: "Pump Is Running" }
  
  system_time: { name: "Controller System Time" }
  controller_firmware_version: { name: "Main Board Firmware" }