substitutions:
  device_name: opnpool-1
  friendly_name: "Test external component OPNpool"
  description: "test external component, see https://medium.com/@vinsce/create-an-esphome-external-component-part-1-introduction-config-validation-and-code-generation-e0389e674bd6"

esphome:
  name: ${device_name}
  comment: ${description}
  friendly_name: ${friendly_name}
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"
  # For debugging, store generated code in an accessible location:
  # build_path: "../config/esphome/component_build"

esp32:
  variant: ESP32
  board: esp32dev
  framework:
    type: esp-idf # arduino

logger:
  #baud_rate: 0
  
wifi:
  domain: !secret domain_name
  min_auth_mode: WPA2
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap: # enable fallback ap captive portal in case wifi connection fails
    ssid: "${device_name} Config"
    password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key 

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time  

web_server:
  port: 80
  include_internal: true

captive_portal:
    

external_components:
  - source: 
      type: local
      path: components

uart:
  id: uart_bus
  rx_pin: GPIO25
  tx_pin: GPIO26
  flow_control_pin: GPIO27
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  debug:
    direction: BOTH

opnpool:
  uart_id: uart_bus

  # climate thermostats
  pool_heater:
    name: "Pool Heater"
  spa_heater:
    name: "Spa Heater"

  # circuit switches
  pool:
    name: "Pool Mode"
  spa:
    name: "Spa Mode"
  aux1:
    name: "Vacuum"
  aux2:
    name: "Light"

  # feature switches
  feature1:
    name: "Feature 1"
  feature2:
    name: "Feature 2"
  feature3:
    name: "Feature 3"
  feature4:
    name: "Feature 4"

  # analog sensors
  water_temperature:
    name: "Pool water"
    state_class: "measurement"
    device_class: "temperature"
    unit_of_measurement: "°F"
  air_temperature:
    name: "Outside air"
    state_class: "measurement"
    device_class: "temperature"
    unit_of_measurement: "°F"
  pump_power:
    name: "Pump power"
    state_class: "measurement"
    device_class: "power"
    unit_of_measurement: "W"
  pump_flow:
    name: "Pump flow"
    state_class: "measurement"
    device_class: "volume_flow_rate"
    unit_of_measurement: "gal/min"
  pump_speed:
    name: "Pump speed"
    state_class: "measurement"
    unit_of_measurement: "rpm"
  chlorinator_level:
    name: "Chlorinator level"
    unit_of_measurement: "%"
  chlorinator_salt:
    name: "Chlorinator salt"
    state_class: "measurement"
    unit_of_measurement: "ppm"

  # binary sensors
  pump_running:
    name: "Pump running"
    device_class: "running"
  mode_service:
    name: "Service mode"
  mode_temperature_inc:
    name: "Temperature increase mode"
  mode_freeze_protection:
    name: "Freeze protection mode"
  mode_timeout:
    name: "Timeout mode"

  # text sensors
  pool_sched:
    name: "Pool schedule"
  spa_sched:
    name: "Spa schedule"
  aux1_sched:
    name: "Aux1 schedule"
  aux2_sched:
    name: "Aux2 schedule"
  pump_mode:
    name: "Pump mode"
  chlorinator_name:
    name: "Chlorinator name"
  chlorinator_status:
    name: "Chlorinator status"
  system_time:
    name: "Controller System Time"
  controller_firmware_version:
    name: "Main Board Firmware"
  interface_firmware_version:
    name: "Interface Board Firmware"

  # number sensors
  pump_status:
    name: "Pump Status"
  pump_state:
    name: "Pump State"
  pump_error:
    name: "Pump Error"

  # debug levels (others default to INFO)
  debug:
    datalink: VERBOSE
    pool_task: DEBUG
    mqtt_task: WARN
